name: equatable_lint
version: 0.2.3
description: This is a set of rules to make classes using Equatable more maintainable. We make sure here that every fields in an Equatable class is linked to the Equatable props getter.
homepage: https://github.com/bamlab/equatable_lint
repository: https://github.com/bamlab/equatable_lint

environment:
  sdk: ">=2.19.0 <3.0.0"

dependencies:
  analyzer: ^5.12.0
  analyzer_plugin: ^0.11.2
  collection: ^1.17.1
  custom_lint_builder: ^0.4.0
  equatable: ^2.0.5
  source_gen: ^1.3.2
